apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mcp-launcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mcp-launcher
subjects:
  - kind: ServiceAccount
    name: mcp-launcher
    namespace: mcp-system
